# This workflow will
# - build, test, and publish the nodejs package
# - create a github release
# - upload native binaries
# when a new version tag is pushed to the master branch.
name: Build Release Publish

on:
  push:
    tags: [v*]

jobs:

  publish_npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Version Information
        run: |
          node --version
          npm --version

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}

  upload_builds:

    needs: create_release

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Version Information
        run: |
          node --version
          npm --version

      - name: Install
        run: npm install
      - name: Test
        run: npm test

      - name: Build for ${{ matrix.os }}
        run: npm run prebuild

      - name: Upload builds for ${{ matrix.os }}
        env:
          PREBUILD_TOKEN: ${{ github.token }}
        shell: bash
        run: npm run prebuild:upload "$PREBUILD_TOKEN"
